### ISSUE TITLE
Add support for RunnerScaleSet

### ISSUE THREAD

**Issue by jalvarezit** [zhaofengli/kubevirt-actions-runner#2]
This project uses old `RunnerDeployment` which are deprecated acording to the [docs](https://github.com/actions/actions-runner-controller#getting-started):

> With the introduction of https://github.com/actions/actions-runner-controller/discussions/2775, the existing [autoscaling modes](https://github.com/actions/actions-runner-controller/blob/master/docs/automatically-scaling-runners.md) are now legacy. The legacy modes have certain use cases and will continue to be maintained by the community only.

Testing it out with the new `RunnerScaleSet` the project does not seem to work.

Steps to reproduce:

* Setup github action runner controller following the [quickstart](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/quickstart-for-actions-runner-controller)
* Create [this](https://github.com/zhaofengli/kubevirt-actions-runner/blob/main/nixos-vm/vm-template.yml) `VirtualMachine` object.
* Setup RBAC as in the README
* Add the following to the `RUnnerScaleSet` template spec:

  ```yaml
    serviceAccountName: kubevirt-actions-runner
      image: ghcr.io/zhaofengli/kubevirt-actions-runner:latest
      repository: org/repo

      # To prevent ARC from starting a separate container
      dockerdWithinRunnerContainer: true
  ```
